name: Release
on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - edited

permissions:
  contents: write

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: archive
      run: |
        echo "Archiving blog posts..."
        zip book-review-list.zip -r blog/**.md  -x "*20240907_report-of-web-developer-conference-2024.md" "*20240503_book-review-how-to-question_book-cover.md"
        tar --exclude "*20240907_report-of-web-developer-conference-2024.md" --exclude "*20240503_book-review-how-to-question_book-cover.md"-zcvf book-review-list.tar.gz blog/**.md

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        files: |
          book-review-list.zip
          book-review-list.tar.gz
        fail_on_unmatched_files: true