name: Release
on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - edited

permissions:
  contents: write

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - run: npm install

    - name: Build
      run: npm run archive:bookReview

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        files: |
          - book-review-list.zip
          - book-review-list.tar.gz
        fail_on_unmatched_files: true